pro/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^$','maim.views.home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cereal_list/$','maim.views.cereal_list'),
    # url(r'^get_view/$', 'maim.views.get_view'),
    #url(r'^get_cereal_manu/$', 'maim.views.get_cereal_manu'),
    url(r'^get_cereal_search/$','maim.views.get_cereal_search'),
    url(r'^cereal_search/(?P<cereal>\w+)/$','maim.views.cereal_search'),
    url(r'^get_manufacturer_search/$', 'maim.views.get_manufacturer_search'),
    url(r'^manu_list/$','maim.views.manu_list'),
    url(r'^manu_search/(?P<manufacturer>\w+)/$', 'maim.views.manu_search'),
    url(r'^nutrinfo/$','maim.views.nutrinfo'),
    url(r'^cereal_list2/$','maim.views.cereal_list2'),
    url(r'^cereal_detail/(?P<pk>\d+)/$','maim.views.cereal_detail'),
    url(r'^form_view/$','maim.views.form_view'),
    url(r'^form_view2/$','maim.views.form_view2'),
    url(r'^cereal_create/$','maim.views.cereal_create'),
    url(r'^signup/$','maim.views.signup'),
    url(r'^home/$','maim.views.home'),
    url(r'^signin/$','maim.views.signin'),
    url(r'^logout/$','maim.views.logout_view'),







] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

maim/models.py
from django.db import models

# Create your models here.


class Cereal(models.Model):
	name = models.CharField(max_length=50, unique=True, null=True)
	serving_size_weight = models.FloatField(null=True)
	cups_per_serving = models.FloatField(null=True)
	display_shelf = models.FloatField(null=True)
	t_ype = models.CharField(max_length=2,null=True)
	manufacturer = models.ForeignKey('maim.Manufacturer', null=True)
	image = models.ImageField(upload_to="cereal", null=True)
	info = models.TextField()

	def __unicode__(self):
		return self.name

	

class NutriFact(models.Model):
	#name = models.CharField(max_length=50)
	calories = models.IntegerField(null=True)
	protein = models.FloatField(null=True)
	fat = models.FloatField(null=True)
	sodium = models.FloatField(null=True)
	dietary_fiber = models.FloatField(null=True)
	carbs = models.FloatField(null=True)
	sugars = models.FloatField(null=True)
	potassium = models.FloatField(null=True)
	vitamins = models.FloatField(null=True)
	Cereal = models.OneToOneField('maim.Cereal', null=True)
	def __unicode__(self):
		return self.Cereal.name
		
	def nutri(self):
		nutri_list=[]
		nutri_list.append("Protein: %s" % self.protein)
		nutri_list.append("Calories: %s " % self.calories)
		nutri_list.append("Fat: %s " % self.fat)
		nutri_list.append("Sodium: %s " % self.sodium)
		nutri_list.append("Dietary Fiber: %s" % self.dietary_fiber)
		nutri_list.append("Carbs: %s " % self.carbs)
		nutri_list.append("Sugars: %s" % self.sugars)
		nutri_list.append("Potassium: %s" % self.potassium)

		return nutri_list

class Manufacturer(models.Model):
	name = models.CharField(max_length=50, null=True)
	def __unicode__(self):
		return self.name

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
{#  #}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title> Cereal List</title>
	<script src="{% static 'JS/jquery-1.11.3.min.js' %}"></script>
	<script src="{% static 'JS/bootstrap.min.js' %}"></script>

	<link rel="stylesheet" type="text/css" href="{% static 'CSS/bootstrap.min.css' %}">

</head>

	<body>
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Cereal</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	{% for m in main_menu %}

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ m.name|slice:':14' }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
          	{% for cereal in m.cereal_set.all %}
            <li><a href="/cereal_detail/{{cereal.pk}}"> {{ cereal }} </a></li>
            {% endfor %}
          </ul>
        </li>

        {% endfor %}


      </ul>
      {% if not user.is_authenticated %}
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Login</button>

      {% else %}
      	<a class="navbar-brand" href="/logout/">Logout</a>
      {% endif %}
      <ul class="nav navbar-nav navbar-right">
      	{% if user.is_authenticated %}
      	<a class="navbar-brand" href="#">{{ request.user }}</a>
      	{% endif %}
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Login</h4>
      </div>
      <div class="modal-body">
      	<form action="/signin/" method="POST" class="navbar-form navbar-left" role="search">
      		<div class="form-group">
      			{% csrf_token %}
      			<input type="text" class="form-control" placeholder="User Name" name="username">
          		<input type="password" class="form-control" placeholder="Password" name="password">
        	</div>
        <button type="submit" class="btn btn-default">Login</button>
        </form>
        </br>
        </br>
       </div>
       <div class="modal-footer">
       		<p>Not a User? Sign Up <a href="/signup/">here</a></p>
      </div>
    </div>
  </div>
</div>
	
		{% block body %}
		{% endblock %}

	</body>
	<script type="text/javascript">
		$(document).ready( function(){
			var alternate=0 
			$('body').css('background-color', '#7DC8FA').css('color','#701637');
			$('.manu_title').css('font-family','Gothic').css('color', 'black');
			$('body').on('click', function() {
				if (alternate % 3 == 0)
				{
					$('body').css('background-color','#709EEF');
				} else if (alternate % 3 == 1)
				{
					$('body').css('background-color', '#8BA6F0');
				} else if (alternate % 3 == 2)
				{
					$('body').css('background-color','#AE92E8');
				}
				alternate+=1;
			});

			$('.nutri').on('mouseover', function(){
				$('.nutri').css('color','#green');
			});
			$('.nutri').on('mouseout', function(){
				$('.nutri').css('color','#white');
			});

		});
	</script>
</html>

templates/cereal_create.html
<form action="/cereal_create/" method="POST">

{% csrf_token %}

{{ form.as_p }}

<input type='submit' value='Save Cereal'>

</form>
{{valid}}

templates/cereal_detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-lg-6">



				<h3>{{cereal.name}}</h3>
				<img src="/media/{{ cereal.image }}">
			</div>
			<div class="col-md-6">	
				<ul>
					<li><b>Manufacturer:</b> {{cereal.manufacturer}}</li>

					{% for fact in cereal.nutrifact.nutri %}
						<li>{{fact}}</li>

					{% endfor %}

				</ul>
			<div class="row">
				<div class="col-lg-7">

					<p><b>{{ cereal.info }}</b></p>
				</div>
			</div>
			</div>
		</div>
	</div>



	

{% endblock %}

templates/cereal_list.html
{% extends "base.html" %}

{% block body %}

		<div class="container">
			<div class="row">
			{% for nutrifact in nutrifacts %}
				<div class="col-xs-6 col-sm-6 col-md-6">
					<h2  class="manu_title">{{ nutrifact.Cereal.name }}</h2><br>
				
						<p class="nutri">{{  nutrifact.nutri }}</p><br>

				</div>
			{% endfor %}
			</div>
		</div>

{% endblock %}

templates/cereal_list2.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}

		<div class="container">
			<div class="row">
				{% for manu, cereals in manufacturer_cereal.items %}
					<div class="col-xs-6 col-sm-6 col-md-6">
						<h2 class="manu_title"><b>{{  manu }}</b></h2><br>

						{% for cereal in cereals %}
							<a href="/cereal_detail/{{cereal.pk}}/">{{ cereal.name }}</a><br>
						{% endfor %}
					</div>
				{% endfor %}
			</div>
		</div>
{% endblock %}

templates/form_view.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}
	<form action ='/form_view/' method='POST'>
	{% csrf_token %}
	Cereal:
	</br>
	<input type="text" name="cereal">

	</br>
	<input type ="submit" value="Submit">
	</form>

	</br>
	</br>
	Method: {{ method }}
	</br>
	Get: {{ get }}
	</br>
	Post: {{ post }}
	</br>
	</br>
	{% for cereal in cereals %}
		{{cereal.name}}</br>
	{% endfor %}

{% endblock %}

templates/form_view2.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}
	<form action ='/form_view2/' method='POST'>
	{% csrf_token %}
	Cereal:
	</br>
	{{ form.as_p}}

	
	<input type ="submit" value="Submit">
	</form>
	
	Valid: {{ valid }}

	</br>
	</br>
	Method: {{ method }}
	</br>
	Get: {{ get }}
	</br>
	Post: {{ post }}
	</br>
	</br>
	{% for cereal in cereals %}
		{{cereal.name}}</br>
	{% endfor %}

{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block body %}



{% endblock %}

templates/logout.html
{% extends "base.html" %}

{% block body %}

	{{ 'Come again Sooon'}}




{% endblock %}

templates/signin.html
{% extends "base.html" %}

{% block body %}




{% endblock %}

templates/signup.html
{% extends "base.html" %}

{% block body %}

<form action="/signup/" method="POST">

	{% csrf_token %}

	{{ form.as_p }}

	<input type='submit' value='Sign Up!'>
	

</form>

{% endblock %}